### PR TITLE
Update BioGeography.md

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
Deleted repetition of first three paragraphs

### CODE REVIEW

**Comment by peterjc** [comment]
@nmatzke Are you happy with this (former wiki) webpage change for BioGeography?

**Comment by MarkusPiotrowski** [comment]
Maybe I was not clear enough, it's not related to content: The first three paragraphs (**Introduction**, **Summary** and **Summary of functions) were 100% duplicated.

**Comment by peterjc** [comment]
I must have looked at the post-commit file, because I couldn't see the problem. It makes sense to me now, thanks.

**Comment by nmatzke** [comment]
Yep, any changes are fine with me!

**Pull request merged**
