### PR TITLE
Broken links on start page

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
For whatever reason, the relative links on the starting page didn't work any longer (urls missed ```\wiki\```).
They work fine on the other pages. 
So hardcoded missing ```wiki\```.
Also hardcode ```http:\\biopython.org``` on ```404.html```, since ```site.baseurl``` didn't proved to be useful (calling the same non-existing page)

### CODE REVIEW

**Comment by peterjc** [comment]
Ah - this would be because now it is effectively at http://biopython.org/index.html rather than being at http://biopython.org/wiki/Biopython.html

**Comment by peterjc** [comment]
Maybe we should use ``/wiki/...`` in the links from that page?

**Comment by peterjc** [comment]
And I should have said earlier: Thank you for spotting this & submitting a fix - I should tested my change for #121 more carefully.

**Comment by MarkusPiotrowski** [comment]
You're welcome!

> Maybe we should use /wiki/... in the links from that page?

Sorry, I don't understand this comment. Where to put it?

**Comment by peterjc** [comment]
Right now you have relative links like ``wiki/Download``, but would an absolute link like ``/wiki/Download`` be more robust?

Also should we move the actual file from ``wiki/Biopython.md`` to the top level folder to make this more obvious when working on the markdown files?

**Pull request merged**
