### PR TITLE
Use relative_url filter consistently and set baseurl to empty

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**
Follow-on PR, according to discussion on #180 

Does seem to work, applied here: https://markuspiotrowski.github.io/

### CODE REVIEW

**Comment by peterjc** [comment]
Thank you!

**Comment by LalitNM** [comment]
@MarkusPiotrowski this needs to be done in some other places too, two of them are listed below, not sure if there are none other than these.
- https://github.com/biopython/biopython.github.io/blob/3e4d073472c89af3477137e92c423f44dd3a6caf/_includes/sidebar.html#L16

- https://github.com/biopython/biopython.github.io/blob/3e4d073472c89af3477137e92c423f44dd3a6caf/_layouts/wiki.html#L7

When I render this site on https://lalitnm.github.io/biopython.github.io (rather than https://lalitnm.github.io), these links do not work.

**Comment by MarkusPiotrowski** [comment]
@LalitNM Actually, I feared that there are possibly more places where this needs to be done...
Do you want to give it a try?

**Comment by LalitNM** [comment]
Sure, but I might need your help...

**Pull request merged**
