### PR TITLE
Issue 79 + 82

### PR DESCRIPTION
**Pull request by mgudapak**
Summary of changes
- Some housekeeping to help with local set up of Jekyll
- Updated README to include instructions for setting up local Jekyll dev env (issue #79)
- Updated README to also use same style as the rest of the site (issue #82) 

P.S. - Sorry about clubbing fixes for two issues together in one pull request but they are closely related.

### CODE REVIEW

**Comment by peterjc** [comment]
I've cherry-picked a couple of these suggestions, thank you.

Do you have strong views on line wrapping in the markdown files? I deliberately used hard line wrapping with pandoc to avoid overly long lines in the markdown where possible.

Are you comfortable with rebasing and force-pushing to a branch to update a pull request on GitHib?

**Comment by mgudapak** [comment]
@peterjc - no strong views on line wrapping. I didn't realize it was intentional - they just wrapped odd as I was resizing my screen while working so I removed them. No worries at all on it.

I haven't done rebasing and force-pushing to a branch .. if you can teach me how or point me to something that does I'd be more than happy to.

thanks!

**Comment by peterjc** [comment]
Good idea, I opened #84 on updating http://biopython.org/wiki/GitUsage

**Comment by peterjc** [comment]
Basic idea for re-basing and updating this pull request:

``` bash
$ git fetch origin
$ git checkout issue-79
$ git rebase origin/master
...
```

Bad case, you need to merge stuff. Here the abort option would be:

``` bash
$ git rebase --abort
```

Then you should be back to where things were.

Good case, it just works (and this is what I would expect as I only cherry-picked a few of your changes so git should spot this and cope smoothly). In which case, assuming you named your fork https://github.com/mgudapak/biopython.github.io as ``mgudapack`` when you did ``git add remote ...``, then:

``` bash
$ git push mgudapack issue-79 --force
```

This is about the only time you should ever do a force-push! This will update the branch ``issue-79`` on your github fork, i.e. https://github.com/mgudapak/biopython.github.io/tree/issue-79 - rewriting the original branch history. GitHub will automatically update this pull request since it is using this branch.

**Pull request closed without merging**
