### PR TITLE
Explaining the policy is used for modules, methods, functions.

### PR DESCRIPTION
**Pull request by svalqui**
Adding more detail, explaining the policy is used for modules, methods, functions and classes.

### CODE REVIEW

**Comment by mdehoon** [comment]
I think this is too restrictive. The current version says 
"**Consider** declaring the module as "obsolete" for a release *before* deprecation."
The updated version makes this a requirement. However, as declaring a module obsolete without deprecating it only helps users that read the source code, this step is mostly pointless. Additionally, in some cases it is preferable to deprecate code immediately. For example if a new module is added to Biopython to replace an older module, then it's better to point users to the new module right away.
Keep in mind that there is a large cost associated with keeping obsolete and deprecated code in Biopython, both for developers and for users, and the sooner obsolete code can be removed from Biopython, the better.

**Comment by svalqui** [comment]
Hi @mdehoon , how about just leaving "We use the same process to deprecate obsolete modules, methods, functions and classes."; at them moment the policy focus on modules; If a contributor wants to remove obsolete methods, there is no information on how to proceed.
What do you think?

**Comment by peterjc** [comment]
I didn't see the first draft of the PR, the updated one seems reasonable - I think we do this in practice.

Another point the page does not currently mention is we have started to use ``PendingDeprecationWarning`` at the ``OBSOLETE`` stage (this is a built in warning, and silent by default), again a recommendation rather than a must.

(We don't use the built in ``DeprecationWarning`` *because* it is silent by default)

**Comment by mdehoon** [comment]
@svalqui  OK, thanks.

**Comment by peterjc** [comment]
TravisCI failed,

```
$ if grep -n -r '[[:blank:]]$' wiki/*.md; then echo 'Please remove trailing whitespace.'; false; fi
wiki/Deprecation_policy.md:13:We use the same process to deprecate obsolete modules, methods, functions 
Please remove trailing whitespace.
```

**Pull request merged**
