### PR TITLE
Added favicon

### LINKED ISSUE #86: Creating a Biopython favicon
We can try basing this on https://github.com/biopython/biopython.github.io/commit/f5f346375d78d86e65f2c4fc04c2394938eba5e7 but I suspect this will be a challenge due to the typical scale. Perhaps a tiny yellow snake is enough?

See also #25.

### PR DESCRIPTION
**Pull request by LalitNM**
@peterjc, @JoaoRodrigues and @MarkusPiotrowski 
Have a look at this pull request and let me know if something else can be merged with this pull request(e.g. removing [apple-touch-icon-144.png](https://github.com/biopython/biopython.github.io/blob/master/apple-touch-icon-144.png)

This fixes #86.

### CODE REVIEW

**Comment by peterjc** [comment]
Could you update ``apple-touch-icon-144.png`` too? It still uses the old icon.

**Review by peterjc — APPROVED** [review]

**Comment by LalitNM** [comment]
I updated `apple-touch-icon.png`. Have a look.

**Comment by peterjc** [comment]
Was it deliberate to rename ``apple-touch-icon-144.png`` to ``apple-touch-icon.png``? I'd have to remind my self of the Apple conventions here, but I thought the name might have some meaning.

**Comment by LalitNM** [comment]
After your comment I read about this on [developer.apple.com](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html). According to them it is enough to keep the file as `apple-touch-icon.png`. We can even remove the `<link>` from `head.html`.

The problem is with the resolution of image, maximum resolution is `180x180`, but at present we are adding a file with resolution`144x144`. Should I add the image with higher resolution?

**Comment by MarkusPiotrowski** [comment]
As far as I have understood it is practice now to provide several favicon.png files with different resolutions:
https://stackoverflow.com/questions/2268204/favicon-dimensions
https://stackoverflow.com/questions/4014823/does-a-favicon-have-to-be-32x32-or-16x16
https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/

So you can decide to put something like 7-... different sized favicons to support an optimal look on each plattform/browser or to put something like 3 files, one being a 32x32 png, one being an high-resolution apple-touch icon and possibly a high-resolution png.

**Comment by LalitNM** [comment]
@MarkusPiotrowski idea of adding multiple images looks good. The problem I pointed out in [this](https://github.com/biopython/biopython.github.io/issues/86#issuecomment-725936070) comment can be fixed by applying an image with transparent background. I am thinking to add html markup and images generated by [realfavicongenerator.net](https://realfavicongenerator.net). This will automatically add images for different devices.

**Review by peterjc — APPROVED** [review]
Seems fine, but I am not up to date with best practises here. Over to @MarkusPiotrowski or @JoaoRodrigues to second and/or merge.

**Comment by LalitNM** [comment]
@JoaoRodrigues and @MarkusPiotrowski would you like to review this?

**Comment by MarkusPiotrowski** [comment]
I have merged the changes to my local branch and pushed it here:
http://markuspiotrowski.github.io/

As far as I can tell it looks good on Windows 10 in Firefox and Edge browser but not so nice as tile (because the tile background is also blue). Actually, this was the first time that I added a webpage as "app" on Windows, so I think this is a very rare scenario and we can live with that.
It also looks nice on an Android tablet (as icon and in Chrome browser). 
If anyone wants to check this on Apple devices, please do so, I'm going to merge this tomorrow.

**Comment by peterjc** [comment]
Tiny tab/bookmark icon looks good on macOS Chrome, Firefox and Safari.

Home screen icon looks good on iPhone.

**Comment by MarkusPiotrowski** [comment]
@LalitNM Good work, thank you!

**Pull request merged**
