### PR TITLE
ProtParam, Publication (and Documentation)

### PR DESCRIPTION
**Pull request by MarkusPiotrowski**

### CODE REVIEW

**Comment by peterjc** [comment]
The ``// text`` lines were notes about the paper which the old plugin would render nicely. Perhaps we can just put them in italics?

**Comment by MarkusPiotrowski** [comment]
Sorry, I didn't know how they looked before. I kept these `//` also in the references in `Dokumentation`.
Now converted them to make the comments italic.

**Comment by MarkusPiotrowski** [comment]
I wonder if I can squash my commits *after* I had made the pull request?

**Comment by peterjc** [comment]
You can update the branch locally (e.g. ``git rebase -i origin/master``) and then force push it here under the same branch name (``git push markus Prot_Pub --force``) and then GitHub will update the pull request.

Or just leave it as multiple commits and I'll squash it if I think it helps.

**Comment by MarkusPiotrowski** [comment]
Thanks for your help. Commits squashed into one.

**Comment by peterjc** [comment]
Thanks Markus.

Minor: Journal names are typically in italics in most reference styles.

My personal preference would be to make the paper title into the URL (not the journal and page numbers).

Nice to see the species names in paper titles are in italics :)

P.S. Extra asterisk at the start of msatcommander?

**Comment by MarkusPiotrowski** [comment]
I made the journal names italic and removed the extra asterisk. Regarding making the title into the URL I disagree. Sometimes the titles span several lines and having this styled as a link doesn't look so nice, in my view. Apart from that, changing this would require to change everthing manually or semi-manually (for my script I have to copy the pmid, it returnes a single formatted reference that I have to copy/paste),

**Comment by peterjc** [comment]
OK - let's go with this, its a big improvement - thank you again Markus!

**Pull request merged**
