### PR TITLE
Move packages info to its own page

### PR DESCRIPTION
**Pull request by peterjc**
This moves a large chunk of the downloads page into its own new page, and documents using conda #118.

Cross reference https://github.com/biopython/biopython/issues/1295

### CODE REVIEW

**Comment by peterjc** [comment]
@souravsingh what do you think of this website change, cross reference https://github.com/biopython/biopython/pull/1310

**Comment by souravsingh** [comment]
As far as I understand, The only way to get biopython is through ``pip`` or through ``conda```. The ``apt-get`` and ``yum`` commands would fetch old binaries, right?

**Comment by souravsingh** [comment]
We can tell the users to install the dev version of Biopython by cloning the repository and running ``python setup.py install``.

The users would need a C-compiler(gcc or vc9 depending on platform) and Git installed beforehand.

**Comment by peterjc** [comment]
We do cover installing from git in the main README (and it falls under https://github.com/biopython/biopython/issues/1295 too), but this is relevant to the proposed packages page, and not very relevant to the Downloads page.

**Pull request merged**
